dist: trusty
notifications: 
  email: false

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      compiler: gcc

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"
  - $CC --version && $CXX --version

script:
  - mkdir build && cd build
  - cmake .. && make ppcurses && make tests
